---

- name: "apt packages update "
  become: true
  apt:
    update_cache: yes

- name: "packages upgrade"
  become: true
  apt:
    upgrade: yes

- name: "installing dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "habd"
  shell: |
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            source ~/.bashrc
            nvm -v
            nvm install 13.0.0

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes