---

- name: "apt packages update "
  become: true
  apt:
    update_cache: yes

- name: "packages upgrade"
  become: true
  apt:
    upgrade: yes

- name: "installing dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: PM2
    global: yes