---
- name: "Backend dir creation"
  file:
    path: ~/backend
    state: directory

- name: "Ungzip backend archive"
  unarchive:
    src:  ~/project/artifact.tar.gz
    dest: ~/backend

- name: "create environment variables"
  shell: |

    echo "TYPEORM_CONNECTION=${TYPEORM_CONNECTION}" >> "backend/backend/dist/.env"
    echo "TYPEORM_ENTITIES=${TYPEORM_ENTITIES}" >> "backend/backend/dist/.env"
    echo "TYPEORM_HOST=${TYPEORM_HOST}" >> "backend/backend/dist/.env"
    echo "TYPEORM_PORT=${TYPEORM_PORT}" >> "backend/backend/dist/.env"
    echo "TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> "backend/backend/dist/.env"
    echo "TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> "backend/backend/dist/.env"
    echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> "backend/backend/dist/.env"
    echo "TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}" >> "backend/backend/dist/.env"
    echo "TYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR}" >> "backend/backend/dist/.env"

- name: "Node install and Node app Execution using PM2"
  shell: |
    cd /home/ubuntu/backend/backend
    npm install
    cd /home/ubuntu/backend/backend/dist
    pm2 stop default
    pm2 start npm -- run "start:dev"

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save