---
- name: "Backend dir creation"
  file:
    path: ~/backend
    state: directory

- name: "Ungzip backend archive"
  unarchive:
    src:  ~/project/artifact.tar.gz
    dest: ~/backend
    
- name: "create environment variables"
  shell: |
    echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
    echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
    echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"

- name: "Node install and Node app Execution using PM2"
  shell: |

    cd /home/ubuntu/backend/backend
    npm install
    cd /home/ubuntu/backend/backend/dist
    pm2 stop default
    pm2 start npm --start

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save