---
- name: "Backend dir creation"
  file:
    path: ~/backend
    state: directory

- name: "Ungzip backend archive"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Install node dep"
  shell: |
    cd ~/backend
    npm install

- name: "Node app Execution using PM2"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save