---


- name: "create environment variables"
  shell: |
    echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
    echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
    echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"

- name: "upgrade packages"
  apt: 
      upgrade: yes

- name: "Unarchive build artifact"
  unarchive:
      src: "files/build-artifact.tar.gz"
      dest: .

- name: "Start application"
  shell:
      npm install
      pm2 stop default
      pm2 start npm -- start